import { CheckCircleFilled, CloseCircleFilled } from '@ant-design/icons'
import { Alert, Button, Input, Modal, Radio, Select, Space, Steps, Tag, Typography } from 'antd'
import { useEffect, useState } from 'react'

import type { AgentAccountProfile, WslDistribution } from '@teskra/contracts'

import { useTranslation, type TranslationKey } from '../i18n'
import { useAgentStore } from '../stores/agent-store'
import { useAccountProfileStore } from './account-profile-store'
import { isValidAccountSlug, slugifyAccountName } from './account-view-model'
import { LoginTerminalView } from './login-terminal-view'

const STEP_KEYS: readonly TranslationKey[] = [
  'accounts.wizard.step.agent',
  'accounts.wizard.step.name',
  'accounts.wizard.step.runtime',
  'accounts.wizard.step.environment',
  'accounts.wizard.step.signin',
  'accounts.wizard.step.verify',
]

interface AddAccountWizardProps {
  readonly open: boolean
  readonly initialAgentId?: string | undefined
  readonly onClose: () => void
}

/**
 * TASK-104 (Milestone 24 §23) — six-step account creation wizard:
 * Select Agent → Profile Name → Runtime → Create Isolated Environment →
 * Sign In (embedded login terminal, skippable) → Verify. Managed profiles
 * only submit the slug; the configHome path is generated by Main and shown
 * read-only (§48.1).
 */
export function AddAccountWizard({ open, initialAgentId, onClose }: AddAccountWizardProps) {
  const { t } = useTranslation()
  const definitions = useAgentStore((state) => state.definitions)
  const createProfile = useAccountProfileStore((state) => state.createProfile)
  const detectProfile = useAccountProfileStore((state) => state.detectProfile)
  const storeError = useAccountProfileStore((state) => state.error)
  const clearError = useAccountProfileStore((state) => state.clearError)

  const [step, setStep] = useState(0)
  const [agentId, setAgentId] = useState<string | undefined>(initialAgentId)
  const [name, setName] = useState('')
  const [slug, setSlug] = useState('')
  const [slugTouched, setSlugTouched] = useState(false)
  const [runtimeKind, setRuntimeKind] = useState<'windows' | 'wsl'>('windows')
  const [distro, setDistro] = useState<string>()
  const [distributions, setDistributions] = useState<readonly WslDistribution[]>([])
  const [creating, setCreating] = useState(false)
  const [createFailed, setCreateFailed] = useState(false)
  const [profile, setProfile] = useState<AgentAccountProfile>()
  const [loginOpened, setLoginOpened] = useState(false)
  const [loginExit, setLoginExit] = useState<number>()
  const [loginSkipped, setLoginSkipped] = useState(false)
  const [verifying, setVerifying] = useState(false)
  const [verified, setVerified] = useState<AgentAccountProfile>()

  // Reset the whole flow whenever the wizard is (re)opened.
  useEffect(() => {
    if (!open) return
    setStep(0)
    setAgentId(initialAgentId ?? definitions[0]?.id)
    setName('')
    setSlug('')
    setSlugTouched(false)
    setRuntimeKind('windows')
    setDistro(undefined)
    setCreating(false)
    setCreateFailed(false)
    setProfile(undefined)
    setLoginOpened(false)
    setLoginExit(undefined)
    setLoginSkipped(false)
    setVerifying(false)
    setVerified(undefined)
    clearError()
  }, [open])

  useEffect(() => {
    if (!open || runtimeKind !== 'wsl') return
    void window.teskra.runtime.listWslDistributions().then((result) => {
      if (result.ok) setDistributions(result.data)
    })
  }, [open, runtimeKind])

  const effectiveSlug = slugTouched ? slug : slugifyAccountName(name)
  const slugValid = isValidAccountSlug(effectiveSlug)
  const nameValid = name.trim().length > 0 && slugValid
  // §7: a WSL profile must pin a concrete distro — never "the default".
  const runtimeValid = runtimeKind === 'windows' || (distro ?? '').length > 0

  const createEnvironment = async (): Promise<void> => {
    if (agentId === undefined) return
    setCreating(true)
    setCreateFailed(false)
    const created = await createProfile({
      agentId,
      name: name.trim(),
      authType: 'subscription',
      runtime: runtimeKind === 'wsl' ? { kind: 'wsl', distro: distro ?? '' } : { kind: 'windows' },
      slug: effectiveSlug,
    })
    setCreating(false)
    if (created === undefined) {
      // Duplicate slug / name conflicts come back from Main as an IpcResult
      // error — send the user back to rename instead of silently retrying.
      setCreateFailed(true)
      return
    }
    setProfile(created)
  }

  const runVerify = async (): Promise<void> => {
    if (profile === undefined) return
    setVerifying(true)
    const detected = await detectProfile(profile.id)
    setVerifying(false)
    if (detected !== undefined) setVerified(detected)
  }

  const stepValid: readonly boolean[] = [
    agentId !== undefined,
    nameValid,
    runtimeValid,
    profile !== undefined,
    loginSkipped || loginExit !== undefined,
    true,
  ]
  const lastStep = STEP_KEYS.length - 1

  return (
    <Modal
      title={t('accounts.wizard.title')}
      open={open}
      onCancel={onClose}
      width={760}
      destroyOnHidden
      footer={
        <Space>
          {step > 0 && (
            <Button onClick={() => setStep((current) => current - 1)}>
              {t('accounts.wizard.back')}
            </Button>
          )}
          {step < lastStep ? (
            <Button
              type="primary"
              disabled={!stepValid[step]}
              onClick={() => setStep((current) => current + 1)}
            >
              {t('accounts.wizard.next')}
            </Button>
          ) : (
            <Button type="primary" onClick={onClose}>
              {t('accounts.wizard.finish')}
            </Button>
          )}
        </Space>
      }
    >
      <Steps
        className="account-wizard-steps"
        size="small"
        current={step}
        items={STEP_KEYS.map((key) => ({ title: t(key) }))}
      />
      <div className="account-wizard-body">
        {step === 0 && (
          <Radio.Group
            className="account-wizard-agent-options"
            value={agentId}
            onChange={(event) => setAgentId(event.target.value as string)}
            options={definitions.map((definition) => ({
              value: definition.id,
              label: definition.name,
            }))}
            optionType="button"
            buttonStyle="solid"
          />
        )}

        {step === 1 && (
          <Space direction="vertical" size={12} className="account-modal-form">
            <label className="account-field">
              <Typography.Text>{t('accounts.wizard.name.label')}</Typography.Text>
              <Input value={name} onChange={(event) => setName(event.target.value)} />
            </label>
            <label className="account-field">
              <Typography.Text>{t('accounts.wizard.slug.label')}</Typography.Text>
              <Input
                value={effectiveSlug}
                {...(slugValid ? {} : { status: 'error' as const })}
                onChange={(event) => {
                  setSlugTouched(true)
                  setSlug(event.target.value)
                }}
              />
              {!slugValid && (
                <Typography.Text type="danger">{t('accounts.wizard.slug.invalid')}</Typography.Text>
              )}
            </label>
          </Space>
        )}

        {step === 2 && (
          <Space direction="vertical" size={12} className="account-modal-form">
            <Radio.Group
              value={runtimeKind}
              onChange={(event) => setRuntimeKind(event.target.value as 'windows' | 'wsl')}
              options={[
                { value: 'windows', label: t('accounts.wizard.runtime.windows') },
                { value: 'wsl', label: t('accounts.wizard.runtime.wsl') },
              ]}
              optionType="button"
              buttonStyle="solid"
            />
            {runtimeKind === 'wsl' && (
              <label className="account-field">
                <Typography.Text>{t('accounts.wizard.runtime.distro')}</Typography.Text>
                <Select
                  value={distro}
                  onChange={setDistro}
                  {...(runtimeValid ? {} : { status: 'error' as const })}
                  options={distributions.map((distribution) => ({
                    value: distribution.name,
                    label: distribution.name,
                  }))}
                />
                {!runtimeValid && (
                  <Typography.Text type="danger">
                    {t('accounts.wizard.runtime.distroRequired')}
                  </Typography.Text>
                )}
              </label>
            )}
          </Space>
        )}

        {step === 3 && (
          <Space direction="vertical" size={12} className="account-modal-form">
            <Typography.Paragraph type="secondary">
              {t('accounts.wizard.env.body')}
            </Typography.Paragraph>
            {createFailed && (
              <Alert
                type="error"
                showIcon
                message={storeError?.message}
                description={t('accounts.wizard.create.renameHint')}
              />
            )}
            {profile === undefined ? (
              <Button type="primary" loading={creating} onClick={() => void createEnvironment()}>
                {t('accounts.wizard.env.create')}
              </Button>
            ) : (
              <label className="account-field">
                <Typography.Text>{t('accounts.wizard.env.configHome')}</Typography.Text>
                {/* §48.1: generated by Main, never editable. */}
                <Input value={profile.configHome ?? ''} readOnly />
              </label>
            )}
          </Space>
        )}

        {step === 4 && profile !== undefined && (
          <Space direction="vertical" size={12} className="account-modal-form">
            <Typography.Paragraph type="secondary">
              {t('accounts.wizard.signin.body')}
            </Typography.Paragraph>
            {loginSkipped ? (
              <Alert type="info" showIcon message={t('accounts.wizard.signin.skipped')} />
            ) : loginOpened ? (
              <>
                <LoginTerminalView
                  profileId={profile.id}
                  title={profile.name}
                  className="account-login-terminal"
                  onExited={setLoginExit}
                />
                {loginExit !== undefined && loginExit !== 0 && (
                  <Alert
                    type="warning"
                    showIcon
                    message={t('accounts.wizard.signin.exitNonZero', { code: loginExit })}
                  />
                )}
              </>
            ) : (
              <Space>
                <Button type="primary" onClick={() => setLoginOpened(true)}>
                  {t('accounts.wizard.signin.open')}
                </Button>
                <Button onClick={() => setLoginSkipped(true)}>
                  {t('accounts.wizard.signin.skip')}
                </Button>
              </Space>
            )}
          </Space>
        )}

        {step === 5 && profile !== undefined && (
          <Space direction="vertical" size={12} className="account-modal-form">
            <Typography.Paragraph type="secondary">
              {t('accounts.wizard.verify.body')}
            </Typography.Paragraph>
            {verified === undefined ? (
              <Button type="primary" loading={verifying} onClick={() => void runVerify()}>
                {t('accounts.wizard.verify.run')}
              </Button>
            ) : verified.status === 'ready' ? (
              <Space direction="vertical" size={4}>
                <Typography.Text>
                  <CheckCircleFilled className="account-verify-ok" />{' '}
                  {t('accounts.wizard.verify.cliDetected')}
                </Typography.Text>
                <Typography.Text>
                  <CheckCircleFilled className="account-verify-ok" />{' '}
                  {t('accounts.wizard.verify.authAvailable')}
                </Typography.Text>
              </Space>
            ) : (
              <Space direction="vertical" size={8}>
                <Typography.Text>
                  <CloseCircleFilled className="account-verify-fail" />{' '}
                  {t('accounts.wizard.verify.failed', { status: verified.status })}
                </Typography.Text>
                <Space>
                  <Button loading={verifying} onClick={() => void runVerify()}>
                    {t('accounts.wizard.verify.retry')}
                  </Button>
                  <Button onClick={onClose}>{t('accounts.wizard.finish')}</Button>
                </Space>
              </Space>
            )}
            <Tag>{profile.name}</Tag>
          </Space>
        )}
      </div>
    </Modal>
  )
}
